site_name: MAGICC Wiki
site_description: 'Tutorials and guides for the MAGICC lab'
site_url: https://byu-magicc.github.io/wiki
site_author: 'MAGICC lab members'

edit_uri: 'https://github.com/byu-magicc/wiki/edit/main/docs/'

theme:
  name: material
  features:
    - content.action.edit
    - navigation.tabs
  palette:
    primary: custom
    accent: custom
  favicon: assets/favicon-16x16.png
  logo: assets/logo.svg

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - codehilite:
      linenums: false
      guess_lang: false
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Safety: safety.md
  - ROS2 Tutorials:
      - "Lesson 1: Introduction to ROS2": ros2_tutorials/intro.md
      - "Lesson 2: Starting Nodes": ros2_tutorials/starting_nodes.md
      - "Lesson 3: Getting Info About Nodes": ros2_tutorials/node_info.md
      - "Assignment 1: Running Nodes: Listener and Talker": ros2_tutorials/assignments/1_L1-3_node_running.md
      - "Assignment 2: Turtlesim Assignment": ros2_tutorials/assignments/2_L1-3_turtlesim.md
      - "Lesson 4: The ROS Filesystem": ros2_tutorials/filesystem.md
      - "Lesson 5: Launch Files": ros2_tutorials/launch_files.md
      - "Assignment 3: Launch Files": ros2_tutorials/assignments/3_L4-5_creating_launch_file.md
      - "Assignment 4: Launch Files": ros2_tutorials/assignments/4_L4-5_explaining_launch_file.md
      - "Lesson 6: ROS2 Topics": ros2_tutorials/rostopic.md
      - "Assignment 5: Nodes, Topics and Messages": ros2_tutorials/assignments/5_L6_nodes_topics_and_messages.md
      - "Lesson 7: Topic Remapping": ros2_tutorials/topic_remapping.md
      - "Lesson 8: ROS2 Parameters": ros2_tutorials/parameters.md
      - "Lesson 9: Additional Launch File Syntax": ros2_tutorials/adv_launch_file.md
      - "Assignment 6: More Launch File Practice 1": ros2_tutorials/assignments/6_L7-9_more_launch_file1.md
      - "Assignment 7: More Launch File Practice 2": ros2_tutorials/assignments/7_L7-9_more_launch_file2.md
      - "Assignment 8: Creating a Launch File with Parameters and Topic Remapping": ros2_tutorials/assignments/8_L7-9_launch_file_advanced.md
      - "Assignment 9: diting Teleop Twist Joy Node": ros2_tutorials/assignments/9_L7-L9_edit_node.md
      - "Lesson 10: Creating Nodes": ros2_tutorials/creating_nodes.md
      - "Lesson 11: Packages": ros2_tutorials/packages.md
      - "Lesson 12a: Nodes Based on Classes (C++)": ros2_tutorials/c++_node_class.md
      - "Lesson 12b: Nodes Based on Classes (Python)": ros2_tutorials/python_node_class.md
      - "Assignment 10: Draw a Star": ros2_tutorials/assignments/10_L10-12_draw_a_star.md
      - "Assignment 11: Display/Publish Fuel Remaining": ros2_tutorials/assignments/11_L10-12_fuel.md
      - "Assignment 12: Stop Turtlesim When Fuel Runs Out": ros2_tutorials/assignments/12_L10-12_out_of_fuel.md
      - "Lesson 13: ROS2 on Multiple Machines": ros2_tutorials/multiple_machines.md
      - "Lesson 14: Others": ros2_tutorials/others.md
      - "Lesson 15: Motion Capture Tutorial": ros2_tutorials/mocap/mocap_tutorial.md
  - Gazebo Tutorials:
      - "Lesson 0: Overview": gazebo_tutorials/overview.md
      - "Lesson 1: Make a Robot": gazebo_tutorials/make_a_robot.md
      - "Lesson 2: Adding Plugins": gazebo_tutorials/adding_plugins.md
      - "Assignment 1: Make a Multirotor": gazebo_tutorials/assignments/make_a_multirotor.md
      - "Assignment 2: Make a Fixed Wing MAV": gazebo_tutorials/assignments/make_a_fixed_wing_mav.md
      - "Lesson 3: Interfacing with Gazebo": gazebo_tutorials/interfacing_with_gazebo.md
      - "Assignment 3: Flying Your MAV": gazebo_tutorials/assignments/flying_your_mav.md
      - "Lesson 4: Make a World": gazebo_tutorials/make_a_world.md
      - "Assignment 4: Make Your Own World": gazebo_tutorials/assignments/make_your_own_world.md
      - "Lesson 5: Adding an Image to the Ground Plane": gazebo_tutorials/adding_an_image_to_the_ground_plane.md
  - Control Tutorials:
      - "Lesson 0: Overview": control_tutorials/overview.md
      - "Lesson 1: P Controller": control_tutorials/p_controller.md
      - "Assignment 0: P Controller with TurtleSim": control_tutorials/assignments/p_turtle.md
      - "Lesson 2: PD Controller": control_tutorials/pd_controller.md
      - "Assignment 1: PD Controller with TurtleSim": control_tutorials/assignments/pd_turtle.md
      - "Lesson 3: PID Controller": control_tutorials/pid_controller.md
      - "Assignment 2: PID Controller with TurtleSim": control_tutorials/assignments/pid_turtle.md
  - Hardware Guides:
      - Pixhawk: computers/pixhawk.md
      - NVIDIA Jetson TX2: computers/jetson.md
      - Raspberry Pi Zero W: hw_guides/rospberry_pi_zero.md
      - CUDA and GPGPUs: hw_guides/gpu.md
      - Ubiquiti: hw_guides/ubiquiti.md
      - "RTK GPS: ZED-F9P": hw_guides/ublox_f9p.md
      - "RTK GPS: C94-M8P": hw_guides/c94_m8p.md
      - ASUS Xtion Pro Live: hw_guides/asus_xtion_pro_live.md
      - Intel RealSense D4xx: hw_guides/intel_rs_d400.md
      - Lithium-Polymer Batteries (Li-Po): hw_guides/lipo_batts.md
      - Battery Charger Guide: hw_guides/charging_lipo_batts.md
      - Designing a Propulsion System: hw_guides/design_propulsion_system.md
  - Software Guides:
      - Intro to Ceres Solver: sw_guides/ceres_solver.md
      - Installing CUDA: sw_guides/install_cuda.md
      - OpenCV with CUDA: sw_guides/opencv.md
      - Python Know-how: sw_guides/python.md
      - Mocap Room Tutorial: sw_guides/mocap_room_tutorial.md
      - UBLOX_read Documentation: sw_guides/ublox_read.md
      - Airsim Quickstart Guide: sw_guides/airsim_quickstart.md
      - Airsim Settings: sw_guides/airsim_settings.md
      - VTOL AirSim Quickstart Guide: sw_guides/vtol_airsim_qs_guide.md
  - Administration:
      - Getting Started with Research: administration/getting_started_in_research.md
      - New Lab-member Tips: administration/new_member_tips.md
      - Conference Room Schedule: administration/conference_room_schedule.md
  - Misc:
      - Startup Scripts with systemd: computers/systemd.md
      - Headless vs Graphical Linux: computers/headless.md
      - CAEDM Integration: misc/caedm_integration.md
      - Debugging ROS Nodes: misc/debugging_ros_nodes.md
      - Environment Setup: misc/env_setup.md
      - Qt Creator: misc/qt_creator.md
      - ROS Command Cheat Sheet: misc/ros_command_cheat_sheet.md
      - Setting Up ssh: misc/setting_up_ssh.md
      - Syncing Time: misc/syncing_time.md
      - Using Git: misc/using_git.md
      - Using Vim: misc/using_vim.md
      - VPN Setup: misc/vpn_setup.md

